### ISSUE TITLE
Metatables

### ISSUE THREAD

**Issue by nico-abram** [groverburger/lovecraft#4]
https://github.com/groverburger/lovecraft/blob/master/engine.lua#L19-L132
Is there any reason you don't use metatables for this?
You can even try using something like https://github.com/kikito/middleclass or, if you want something a bit faster, with a smaller footprint (But less features) that uses the same API and can be upgraded to middleclass at any point https://github.com/Positive07/lowerclass

**Comment by groverburger** [comment]
in my opinion metatables aren't very readable so i don't use them. i may in the future if i find a use case that would somehow be perfect for metatables, but that has yet to happen

i'm not switching to a different object orientation pattern this late into the project. what would the advantages to switching to middleclass or lowerclass be over what i'm currently doing?

**Comment by groverburger** [comment]
I do not agree with anything I said in that comment anymore lmao
